// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYDzF5l9qArD-zSrsONTM344S6CIPAapQ',
    appId: '1:730341362424:web:52832975d1325ade94890d',
    messagingSenderId: '730341362424',
    projectId: 'eventmngmt-1deb7',
    authDomain: 'eventmngmt-1deb7.firebaseapp.com',
    storageBucket: 'eventmngmt-1deb7.firebasestorage.app',
    measurementId: 'G-0B66MGSJ27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX4bGr9K8j2uT0k7AxNES4JKWTuAJc2p0',
    appId: '1:730341362424:android:9c5dceabc46239a894890d',
    messagingSenderId: '730341362424',
    projectId: 'eventmngmt-1deb7',
    storageBucket: 'eventmngmt-1deb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv308y_mcyHk40MmsYlUk8cYiDEhHK4os',
    appId: '1:730341362424:ios:8dfe96ce6949ad7a94890d',
    messagingSenderId: '730341362424',
    projectId: 'eventmngmt-1deb7',
    storageBucket: 'eventmngmt-1deb7.firebasestorage.app',
    iosBundleId: 'com.example.masterevent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv308y_mcyHk40MmsYlUk8cYiDEhHK4os',
    appId: '1:730341362424:ios:8dfe96ce6949ad7a94890d',
    messagingSenderId: '730341362424',
    projectId: 'eventmngmt-1deb7',
    storageBucket: 'eventmngmt-1deb7.firebasestorage.app',
    iosBundleId: 'com.example.masterevent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYDzF5l9qArD-zSrsONTM344S6CIPAapQ',
    appId: '1:730341362424:web:ce8a3bb298441f1294890d',
    messagingSenderId: '730341362424',
    projectId: 'eventmngmt-1deb7',
    authDomain: 'eventmngmt-1deb7.firebaseapp.com',
    storageBucket: 'eventmngmt-1deb7.firebasestorage.app',
    measurementId: 'G-CQLSQ3X5TK',
  );

}